### ISSUE TITLE
Add a standard README

### ISSUE THREAD

**Issue by Rishabh04-02** [Rishabh04-02/Elective-manager-prototype#1]
Here is a sample minimal standard readme which one can refer [sample](https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md)
OR you can refer this [sample2](https://github.com/Rishabh04-02/Elective-manager/blob/master/README.md)

**Comment by sourabhbit** [comment]
# [Name](http://repolink.io)
It should be linked to the Github domain

<a href="http://respolink.io"><img src="https://assets-cdn.github.com/images/modules/open_graph/github-mark.png" alt="Name: A software" style="max-width:100%;" width="400" height="215"></a>


## Synopsis

At the top of the file there should be a short introduction and/ or overview that explains **what** the project is. This description should match descriptions of repository

## Motivation

A short description of the motivation behind the creation and maintenance of the project. This should explain **why** the project exists.

## Quick install

Provide code examples and explanations of how to get the project.

## Plugins and Extensions

Provide additional plugins for the software

## Platform Support
OS system should be described. and the system configuration should also be mentioned in this

## Tests

Describe and show how to run the tests with code examples.

## Related projects
Projects that is linked with this repository or software should be mentioned

| Project                                                                            | Description                                                        |
|------------------------------------------------------------------------------------|--------------------------------------------------------------------|
| [Project Name](https://github.com/) | Description.                        |


## Contributors

Let people know how they can dive into the project, include important links to things like issue trackers, irc, twitter accounts if applicable.

## Copyright and license

A short snippet describing the license (MIT, Apache, etc.)

**Comment by Rishabh04-02** [comment]
@sourabhbit Interested in taking up the issue?

**Comment by sourabhbit** [comment]
Yes !

**Comment by Rishabh04-02** [comment]
@sourabhbit but i want the readme of this kind [sample](https://github.com/Rishabh04-02/Elective-manager/blob/master/README.md), this sample readme is of the actual project whose prototype is this project (Elective manager prototype).
